#!/usr/bin/env node
const child_process = require('child_process');

console.log('Running fake-python');
const child = child_process.spawn(process.argv[2], process.argv.slice(3));

child.stdout.on('data', function (data) {
    console.log(data.toString());
});

child.stderr.on('data', function (data) {
    console.error(data.toString());
});